### ISSUE TITLE
cephadm-rookify-setup: Waiting for disabled original ceph-rgw host worker1 to disconnect

### ISSUE THREAD

**Issue by boekhorstb1** [SovereignCloudStack/rookify#106]
I added rgw objects, buckets with files, for an own zone, zonegroup and so on. Following setup (see at the end of the yaml file):

```yaml
---
service_type: host
hostname: master
addr: {{ master_ip }}
labels:
  - _admin
  - grafana
---
service_type: host
hostname: worker1
addr: {{ worker1_ip }}
labels:
  - mon
  - mgr
  - mds
  - osd
  - alertmanager
  - rgw
---
service_type: host
hostname: worker2
addr: {{ worker2_ip }}
labels:
  - mon
  - mgr
  - mds
  - osd
  - prometheus
  - rgw
---
service_type: host
hostname: worker3
addr: {{ worker3_ip }}
labels:
  - mon
  - mgr
  - mds
  - osd
  - rgw
---
service_type: alertmanager
service_name: alertmanager
placement:
  count: 1
  hosts: 
    - 'worker1'
---
service_type: prometheus
service_name: prometheus
placement:
  count: 1
  hosts: 
    - 'worker2'
---
service_type: mds
service_id: mds
service_name: mds.mds
placement:
  count: 2
  label: mds
---
service_type: mgr
service_name: mgr
placement:
  count: 2
  hosts:
    - worker1
    - worker2
    - worker3
---
service_type: mon
service_name: mon
placement:
  count: 3
  hosts:
    - worker1
    - worker2
    - worker3
---
service_type: osd
service_name: osd
placement:
  count: 3
  hosts:
    - worker1
    - worker2
    - worker3
crush_device_class: hdd
spec:
  data_devices:
    rotational: true
    size: 10GB
  filter_logic: AND
  objectstore: bluestore
  db_devices:
    rotational: true
    size: 9GB
---
service_type: node-exporter
service_name: node-exporter
placement:
  host_pattern: 'worker*'
---
service_type: crash
service_name: crash
placement:
  host_pattern: 'worker*'
---
service_type: rgw
service_id: testing-eu-east
service_name: rgw.testing-eu-east
placement:
  count: 3
  host_pattern: 'worker*'
spec:
  rgw_zonegroup: eu
  rgw_zone: eu-east
  rgw_realm: eu-east
  rgw_frontend_type: "beast"
  rgw_frontend_port: 8080

# NOTE: rgw object might be created, good, but the config is set elsewhere, which means: the default will not be changed for the zones.
# So current solution: change default afterwards, like this, manually:
#  sudo radosgw-admin zonegroup create --rgw-zonegroup=eu --rgw-realm=eu-east --master --default
#  sudo radosgw-admin zone create --rgw-zonegroup=eu --rgw-zone=eu-east --master --default
#  sudo radosgw-admin zonegroup remove --rgw-zonegroup=default --rgw-zone=default
#  sudo radosgw-admin period update --commit

```

when running migration with `rookify -m` setup hangs at disabling origin ceph-rgw:

```bash
2024-11-18 14:04.38 [info     ] Execution started with machine pickle file
2024-11-18 14:04.38 [info     ] Validated Ceph to expect cephx auth
2024-11-18 14:04.38 [debug    ] K8sPrerequisitesCheck started validation
2024-11-18 14:04.38 [info     ] Migrating ceph-osd host 'worker1'
2024-11-18 14:04.38 [info     ] Migrating ceph-osd host 'worker2'
2024-11-18 14:04.38 [info     ] Migrating ceph-osd host 'worker3'
2024-11-18 14:04.38 [info     ] Migrating ceph-rgw daemon at host 'worker1'
2024-11-18 14:04.38 [debug    ] Waiting for disabled original ceph-rgw host 'worker1' to disconnect
```

Checking the pods in k3s give following insights:

```bash
rook-ceph     rook-ceph-mgr-a-7bf4754786-mgdvp                    0/3     Pending     0              173m
rook-ceph     rook-ceph-mgr-b-6b8786d97f-b2bjv                    0/3     Pending     0              173m
```

Description of one of those pods shows this:

```bash
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node-role.kubernetes.io/control-plane=true:NoSchedule
                             node-role.kubernetes.io/master=true:NoSchedule
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 5s
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  3m26s (x14 over 68m)  default-scheduler  0/4 nodes are available: 4 node(s) didn't match Pod's node affinity/selector. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.
  ``` 
  
  Will check if this is because of some configurational mistakes of my own, maybe not enough resoruces (RAM?), or otherwise this might be a bug.
